# main common_ops Tasks

# Set timeZone
- name: set timezone to Europe/Paris
  timezone:
    name: Europe/Paris

# Ensure Distro's up to date!
- name: "Update distro's cache"
  apt:
    update_cache: yes

# Update distrib
- name: "Upgrade distro"
  apt:
    force_apt_get: yes
    upgrade: dist
    update_cache: no
  register: upgrade_result

# configure needed packages
- name: "Install base's required packages"
  apt:
    name: "{{ packages }}"
    install_recommends: yes
    update_cache: yes
  vars:
    packages:
        - ufw
        - curl
        - socat
        - sudo
        - wipe
        - htop
        - git
        - openssl

# Ensure Distro's up to date!
- name: "Remove useless packages && dependencies from distro's cache"
  apt:
    force_apt_get: yes
    autoclean: yes

- name: Remove useless dependencies from distro
  apt:
    force_apt_get: yes
    autoremove: yes
