---
# Let's play OP!

# Please take a look at README.md file before you begin using this boilerplate !

- name: "Base server's setup"
  hosts: base
  gather_facts: no
#  become: yes
  remote_user: root # our default user
#  remote_user: <user> # our deployed user
#  become_method: sudo
  vars:
    ansible_port: 22 # default port to connect to
    timezone: "Europe/Paris"
#    ansible_port: 1984 # default port to connect to

  roles:
    - base_deploy
    - base_custom
    - base_ops
