# Install needed packages
- name: "Install MariaDB required packages"
  apt:
    name: "{{ required_packages }}"
    install_recommends: yes
    update_cache: yes

# Add mariaDB repo
- name: Add an apt key MariaDB
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C74CD1D8
    state: present

# Install MariaDB from official sources!
- apt_repository:
    repo: deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.3/debian stretch main
    state: present

# Install MariaDB-server package
- name: MariaDB server installation
  apt:
    name: mariadb-server
    install_recommends: yes
    update_cache: yes

# Set MySQL configuration file (before or after MySQL install)
- name: Setting up configuration file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

# Create database
- name: Create natatrix_net_mail Database
  mysql_db:
    name: "<db_name>"
    state: present

# Add  user to MariaDB
- name: Add nmsusr user to MariaDB
  mysql_user:
    name: <db-usr>
    password: "{{ db_usr_passwd }}"
    priv: '<db_name>.*:ALL'
    host: "localhost"
    state: present

# Enable MySQLDB on startup
- name: Start Mysqld Service on startup
  service:
    name: mysqld
    state: started
    enabled: yes

# restart MysqlDB service!
  notify: restart mysql
